version: "3.9"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - "db"
    environment:
      DOMAIN: "localhost"
      NODE_ENV: development
      PORT: 3000
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: portfolio
      DB_HOST: db
      DB_PORT: 5432
    volumes:
      - ./backend:/app/backend
      - ./frontend:/app/frontend
  db:
    image: "postgres"
    restart: "always"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: portfolio
    volumes:
      - ./backend/database/seeds:/docker-entrypoint-initdb.d
      - ./backend/database/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"