services:
  devcontainer:
    build: .
    volumes:
      - ./../:/workspaces/portfolio
      - devcontainer-zshhistory:/root/commandhistory/.zsh_history
      # Forward docker socket to allow docker commands to be run from within the container
      - /var/run/docker.sock:/var/run/docker.sock
    command: sleep infinity
  app:
    container_name: app-dev
    image: "portfolio"
    build:
      context: ./../
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - "db"
    env_file:
      - ./../.env.local
    volumes:
      - ./../server/src:/app/src
      - ./../server/prisma:/app/prisma
      - ./../client/dist:/app/dist/src/public
    command: yarn dev
  db:
    image: 'postgres'
    restart: 'always'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: portfolio
    ports:
      - '5432:5432'
    volumes:
      - ./db-data:/var/lib/postgresql/data
volumes:
  devcontainer-zshhistory:
