version: "3.9"
services:
  app:
    container_name: portfolio-app
    image: "portfolio"
    build:
      context: $PWD
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - "db"
    environment:
      DOMAIN: "localhost"
      NODE_ENV: development
      PORT: 3000
      DATABASE_URL: "postgres://user:password@db:5432/portfolio"
      ENVIRONMENT: "development"
    volumes:
      - $PWD/server/src:/app/src
      - $PWD/server/prisma:/app/prisma
      - $PWD/client/dist:/app/dist/src/public
    command: yarn dev

  db:
    image: "postgres"
    restart: "always"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: portfolio
    volumes:
      - $PWD/deployments/build/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    command: postgres -c stats_temp_directory=/tmp
